language: node_js
node_js:
  - "7.4"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - "curl https://install.meteor.com | /bin/sh"
  - "export PATH=$HOME/.meteor:$PATH"
notifications:
  webhooks:
    urls:
      - https://api.ghostinspector.com/v1/suites/[suite-id]/execute/?apiKey=[api-key]
    on_success: always
    on_failure: never
