export const USERPROFILE = 'USERPROFILE';
export const SUBSCRIBE = 'SUBSCRIBE';
export const USERPROFILE_SUCCESS = 'USERPROFILE_SUCCESS';
export const USERPROFILE_ERROR = 'USERPROFILE_ERROR';

export const COLLECTION_ADDED = 'COLLECTION_ADDED';
export const COLLECTION_CHANGED = 'COLLECTION_CHANGED';
export const COLLECTION_REMOVED = 'COLLECTION_REMOVED';
export const COLLECTION_REPLACE = 'COLLECTION_REPLACE';
export const COLLECTION_RESET = 'COLLECTION_RESET';
